const MenusActionTypes = {
	FETCH_MENUS_COLLECTIONS_START: 'FETCH_MENUS_COLLECTIONS_START',
	FETCH_MENUS_COLLECTIONS_SUCCESS: 'FETCH_MENUS_COLLECTIONS_SUCCESS',
	FETCH_MENUS_COLLECTIONS_UPDATE: 'FETCH_MENUS_COLLECTIONS_UPDATE',
	FETCH_MENUS_COLLECTIONS_FAILURE: 'FETCH_MENUS_COLLECTIONS_FAILURE',
	CLEAR_MENUS_COLLECTIONS: 'CLEAR_MENUS_COLLECTIONS',
	REMOVE_COLLECTION_LISTENER: 'REMOVE_COLLECTION_LISTENER',
};

export default MenusActionTypes;
