const MenusActionTypes = {
	FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
	FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
	FETCH_COLLECTIONS_UPDATE: 'FETCH_COLLECTIONS_UPDATE',
	FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
	REMOVE_COLLECTION_LISTENER: 'REMOVE_COLLECTION_LISTENER',
};

export default MenusActionTypes;
