const UserActionTypes = {
	GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
	GOOGLE_SIGNIN_SUCCESS: 'GOOGLE_SIGNIN_SUCCESS',
	GOOGLE_SIGNIN_FAILURE: 'GOOGLE_SIGNIN_FAILURE',
	GOOGLE_SIGNOUT_START: 'GOOGLE_SIGNOUT_START',
	REMOVE_USER_LISTENER: 'REMOVE_USER_LISTENER',
	FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
	FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
	FETCH_ALL_USERS_UPDATE: 'FETCH_ALL_USERS_UPDATE',
	FETCH_ALL_USERS_FAILURE: 'FETCH_ALL_USERS_FAILURE',
};

export default UserActionTypes;
