const UserActionTypes = {
	FETCH_USER_START: 'FETCH_USER_START',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
	FETCH_USER_UPDATE: 'FETCH_USER_UPDATE',
	FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
	REMOVE_USER_LISTENER: 'REMOVE_USER_LISTENER',
	FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
	FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
	FETCH_ALL_USERS_UPDATE: 'FETCH_ALL_USERS_UPDATE',
	FETCH_ALL_USERS_FAILURE: 'FETCH_ALL_USERS_FAILURE',
	REMOVE_ALL_USERS_LISTENER: 'REMOVE_ALL_USERS_LISTENER',
};

export default UserActionTypes;
